services:
  arrow-calculator:
    build: .
    container_name: arrow-calculator
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s